version: '3'
services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    networks:
      - test-network
    depends_on:
      - db
    links:
      - db
    ports:
      - "80:80"
      - "443:443"
  php-fpm:
    container_name: test_php
    image: jguyomard/laravel-php:7.3
    volumes:
      - ./:/var/www/
    networks:
      - test-network
  db:
    container_name: test_db
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: secret
    volumes:
      - test-data:/var/lib/mysql
    networks:
      - test-network
    ports:
      - "33060:3306"
networks:
  test-network:
    driver: "bridge"
volumes:
  test-data:
    driver: "local"
